// Code generated by mockery v2.2.1. DO NOT EDIT.

package mocks

import (
	models "github.com/ehabterra/go-site/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// SiteService is an autogenerated mock type for the SiteService type
type SiteService struct {
	mock.Mock
}

// Create provides a mock function with given fields: go_site
func (_m *SiteService) Create(site *models.GoSite) {
	_m.Called(site)
}

// Delete provides a mock function with given fields: id
func (_m *SiteService) Delete(id string) {
	_m.Called(id)
}

// Get provides a mock function with given fields: id, go_site
func (_m *SiteService) Get(id string, site *models.GoSite) {
	_m.Called(id, site)
}

// GetAll provides a mock function with given fields: sites
func (_m *SiteService) GetAll(sites *[]*models.GoSite) {
	_m.Called(sites)
}

// Update provides a mock function with given fields: go_site
func (_m *SiteService) Update(site *models.GoSite) {
	_m.Called(site)
}
